# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=300)),
                ('image_url', models.URLField()),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='QueryNotificationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('notificationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthifyme_Notification_Assignment_REST_App.Notifications')),
            ],
            options={
                'db_table': 'query_notification_mapping',
            },
        ),
    ]
