# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Healthifyme_Notification_Assignment_REST_App', '0002_auto_20170401_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querynotificationmapping',
            old_name='notificationId',
            new_name='notification_id',
        ),
    ]
